export const UPDATE_API_KEY = "UPDATE_API_KEY";
export const UPDATE_SEASON_AND_COUNTRY = "UPDATE_SEASON_AND_COUNTRY";
export const UPDATE_LEAGUE = "UPDATE_LEAGUE";
export const UPDATE_TEAM = "UPDATE_TEAM";